### ISSUE TITLE
Overcurrent Error on Escon Controller

### ISSUE THREAD

**Issue by cumhuronat** [willem-pennings/balancing-cube#5]
I keep getting Overcurrent Error randomly in a few seconds after the cube starts balancing and it causes the cube to fall. The error appears randomly in one of the 3 escon controllers. The error is both visible in the escon studio and with the status led (2 red blinks). I tried regulation tuning as well but it didn't help. Any ideas what might be the problem?
![image_6209779](https://github.com/willem-pennings/balancing-cube/assets/529671/fd86b54b-5b72-4aa7-8dcf-fca1c01f6704)

**Comment by willem-pennings** [comment]
Hello, pleased to see a fully assembled cube! I recognize the error and in my case the problem was that the controller gains are just too high. The values that are obtained through the tuning procedure are no good (too high). Are you using the values from my configuration file?

I am using these values for the current controller (which is the only one you need):

![afbeelding](https://github.com/willem-pennings/balancing-cube/assets/28662192/f1f3e2b9-ed27-4183-a1eb-7d04bc6c0fc1)

**Comment by cumhuronat** [comment]
Thanks for sharing your pid values, will try them and let you know the result. Thanks again for making this opensource!

**Comment by willem-pennings** [comment]
Thanks, I'm curious to know if this gives better results. I just noticed that the gains in my configuration files are wrong so I updated them with the values posted above. It probably explains your issue..!

**Comment by cumhuronat** [comment]
It works like a charm now! Thank you
https://github.com/willem-pennings/balancing-cube/assets/529671/bb86d19a-39b8-46b5-92c9-854b028f8558

**Comment by willem-pennings** [comment]
Excellent, congratulations!
